format_version: 10
pipelines:
  deploy-configs:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-326a400:
        git: https://github.com/gianlcl/fssh
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          get-config:
            timeout: 0
            tasks:
            - exec:
                command: ls
                run_if: passed
