name: Pipeline Build Images

on:
  workflow_dispatch:
    inputs:
      tagging:
        description: "Tag a ser buildada"
        type: choice
        required: true
        default: development
        options:
          - development
          - test-pipeline

permissions:
  packages: write

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@master
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            gianlcl/curl:latest
