# This is a basic workflow that is manually triggered

name: Read Info

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    branches:
    - main
  types: [closed]

jobs:
  greet:
    if: github.event.pull_request.merged == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo -e "Hello World\n$GITHUB_WORKFLOW\n$GITHUB_JOB\n$GITHUB_ACTION\n$GITHUB_ACTOR\n$GITHUB_EVENT_NAME\n\n${{ github.event }}"
